version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "artlogic"
    labels:
      - "dependencies"
      - "github-actions"
